### GET index.html
GET http://127.0.0.1:9090/

### GET version
GET http://127.0.0.1:9090/v0/version
Accept: application/json

### GET docker info
GET http://127.0.0.1:9090/v0/docker/version
Accept: application/json

### GET docker container list
GET http://127.0.0.1:9090/v0/docker/containers
Accept: application/json

### GET docker disk usage
GET http://127.0.0.1:9090/v0/docker/disk-usage
Accept: application/json

### GET docker container log info
GET http://127.0.0.1:9090/v0/docker/log-size
Accept: application/json

### GET docker mounts
GET http://127.0.0.1:9090/v0/docker/mounts-bind
Accept: application/json
