name: build

on:
    push:
      branches:
        - master
        - 39-create-a-new-ciyml
      tags:
        - '*'
      paths-ignore:
        - '*.md'
    pull_request:
      paths-ignore:
        - '*.md'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              run: |
                make info
                make build
                ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
                echo GITHUB_REF - $ref
              env:
                USERNAME: ${{ github.actor }}
                GITHUB_SHA: ${{ github.sha }}
                GITHUB_REF: ${{ github.ref }}

            - name: Test and Lint
              run: |
                make test
                make lint

            - name: Coveralls Report
              run: |
                pip install coveralls
                cd app && coveralls --service=github
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
